// ACTIONS FOR ALERT COMPONENT
export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

// ACTIONS FOR CANDIDATE LOGIN
export const CANDIDATE_LOGIN_BEGIN = "CANDIDATE_LOGIN_BEGIN";
export const CANDIDATE_LOGIN_SUCCESS = "CANDIDATE_LOGIN_SUCCESS";
export const CANDIDATE_LOGIN_ERROR = "CANDIDATE_LOGIN_ERROR";

// ACTIONS FOR CANDIDATE REGISTER
export const CANDIDATE_REGISTER_BEGIN = "CANDIDATE_REGISTER_BEGIN";
export const CANDIDATE_REGISTER_SUCCESS = "CANDIDATE_REGISTER_SUCCESS";
export const CANDIDATE_REGISTER_ERROR = "CANDIDATE_REGISTER_ERROR";

// ACTIONS FOR CLIENT LOGIN
export const CLIENT_LOGIN_BEGIN = "CLIENT_LOGIN_BEGIN";
export const CLIENT_LOGIN_SUCCESS = "CLIENT_LOGIN_SUCCESS";
export const CLIENT_LOGIN_ERROR = "CLIENT_LOGIN_ERROR";

// ACTIONS FOR CLIENT REGISTER
export const CLIENT_REGISTER_BEGIN = "CLIENT_REGISTER_BEGIN";
export const CLIENT_REGISTER_SUCCESS = "CLIENT_REGISTER_SUCCESS";
export const CLIENT_REGISTER_ERROR = "CLIENT_REGISTER_ERROR";

// ACTIONS FOR ADMIN LOGIN
export const ADMIN_LOGIN_BEGIN = "ADMIN_LOGIN_BEGIN";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_ERROR = "ADMIN_LOGIN_ERROR";

// ACTIONS FOR ADMIN REGISTER
export const ADMIN_REGISTER_BEGIN = "ADMIN_REGISTER_BEGIN";
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";
export const ADMIN_REGISTER_ERROR = "ADMIN_REGISTER_ERROR";

// ACTIONS TO LOGOUT A USER
export const LOGOUT_USER = "LOGOUT_USER";