// ACTIONS FOR ALERT COMPONENT
export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

// ACTIONS FOR SETTING UP AUTH FORM DATA
export const SET_AUTH_FORM_DATA = "SET_AUTH_FORM_DATA";

export const AUTH_BEGIN = "LOGIN_BEGIN";
export const AUTH_ERROR = "AUTH_ERROR";

// ACTIONS FOR CANDIDATE LOGIN
export const CANDIDATE_LOGIN_SUCCESS = "CANDIDATE_LOGIN_SUCCESS";

// ACTIONS FOR CANDIDATE REGISTER
export const CANDIDATE_REGISTER_SUCCESS = "CANDIDATE_REGISTER_SUCCESS";

// ACTIONS FOR CLIENT LOGIN
export const CLIENT_LOGIN_SUCCESS = "CLIENT_LOGIN_SUCCESS";

// ACTIONS FOR CLIENT REGISTER
export const CLIENT_REGISTER_SUCCESS = "CLIENT_REGISTER_SUCCESS";

// ACTIONS FOR ADMIN LOGIN
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";

// ACTIONS FOR ADMIN REGISTER
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";

export const SET_JOB_FORM_DATA = "SET_JOB_FORM_DATA";

// ACTIONS TO LOGOUT A USER
export const LOGOUT_USER = "LOGOUT_USER";