// ACTIONS FOR ALERT COMPONENT
export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

// ACTIONS FOR SETTING UP AUTH FORM DATA
export const SET_AUTH_FORM_DATA = "SET_AUTH_FORM_DATA";

export const SET_AUTH_CLIENT_FORM_DATA = "SET_AUTH_CLIENT_FORM_DATA";

export const API_REQUEST_BEGIN = "API_REQUEST_BEGIN";
export const API_REQUEST_ERROR = "API_REQUEST_ERROR";

// ACTIONS FOR CANDIDATE LOGIN
export const CANDIDATE_LOGIN_SUCCESS = "CANDIDATE_LOGIN_SUCCESS";

// ACTIONS FOR CANDIDATE REGISTER
export const CANDIDATE_REGISTER_SUCCESS = "CANDIDATE_REGISTER_SUCCESS";

// ACTIONS FOR CLIENT LOGIN
export const CLIENT_LOGIN_SUCCESS = "CLIENT_LOGIN_SUCCESS";

// ACTIONS FOR CLIENT REGISTER
export const CLIENT_REGISTER_SUCCESS = "CLIENT_REGISTER_SUCCESS";

// ACTIONS FOR ADMIN LOGIN
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";

// ACTIONS FOR ADMIN REGISTER
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";

export const SET_JOB_FORM_DATA = "SET_JOB_FORM_DATA";

// ACTIONS TO LOGOUT A USER
export const LOGOUT_USER = "LOGOUT_USER";

// ACTIONS TO ADD JOB
export const ADD_JOB_SUCCESS = "ADD_JOB_SUCCESS";

// ACTIONS TO DELETE JOB
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";

// ACTIONS TO EDIT JOB
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";

// ACTIONS TO GET CLIENT JOBS
export const GET_CLIENT_JOBS_SUCCESS = "GET_CLIENT_JOBS_SUCCESS";

// ACTIONS TO GET JOBS PARTICULAR TO A CLIENT
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";

// ACTIONS TO GET ALL JOBS
export const GET_ALL_JOBS_SUCCESS = "GET_ALL_JOBS_SUCCESS";

// ACTIONS TO GET SINGLE JOB 
export const GET_SINGLE_JOB_SUCCESS = "GET_SINGLE_JOB_SUCCESS";

// ACTIONS TO GET CLIENT'S DETAILS
export const GET_CLIENT_DETAILS_SUCCESS = "GET_CLIENT_DETAILS_SUCCESS";

// ACTIONS TO APPLY FOR JOB
export const JOB_APPLY_SUCCESSFUL = "JOB_APPLY_SUCCESSFUL";

// ACTIONS TO GET CANDIDATE'S JOBS
export const GET_CANDIDATE_JOBS_SUCCESS = "GET_CANDIDATE_JOBS_SUCCESS";

// ACTIONS TO SAVE A JOB
export const SAVE_JOB_SUCCESS = "SAVE_JOB_SUCCESS";

// ACTION TO GET SAVED JOBS OF A CANDIDATE
export const GET_SAVED_JOBS_SUCCESS = "GET_SAVED_JOBS_SUCCESS";

export const APPLICANT_DETAILS_SUCCESS = "APPLICANT_DETAILS_SUCCESS";